sudo: false
language: cpp
compiler: clang
env:
  - OPENCV_VERSION=2.4.8
  - OPENCV_VERSION=3.1.0
addons:
  apt:
    sources:
      - boost-latest
    packages:
      - libboost1.55-all-dev
cache:
  directories:
    - $HOME/opencv
    - $HOME/cmake
    - $HOME/eigen
    - $HOME/ceres
script:
  - bash .travis.sh
